.\" Manpage for obdi.
.TH man 8 "18 Mar 2015" "0.1.3" "obdi-worker man page"
.SH NAME
obdi-worker \- Obdi worker daemon
.SH SYNOPSIS
obdi-worker
.SH DESCRIPTION
obdi-worker is a daemon for running jobs sent by the obdi daemon.

This daemon is typically started by an init script - not by hand. If started
by hand, from the command line, then logging will be written to the current
terminal.
.SH OPTIONS
obdi does not take any options.
.SH SEE ALSO
obdi(8)
.SH BUGS
See https://github.com/mclarkson/obdi/issues
.SH AUTHOR
Mark Clarkson (mark.clarkson@smorg.co.uk)
